openapi: 3.1.0
info:
  title: Navidrome API
  version: 0.1.0
tags:
  - name: Authentication
  - name: Lists
paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResult"
  /api/artist:
    get:
      tags:
        - Lists
      parameters:
        - $ref: "#/components/parameters/Start"
        - $ref: "#/components/parameters/End"
        - $ref: "#/components/parameters/Sort"
        - $ref: "#/components/parameters/Order"
        - $ref: "#/components/parameters/Starred"
        - $ref: "#/components/parameters/Missing"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Artist"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthenticatedError"
  /api/album:
    get:
      tags:
        - Lists
      parameters:
        - $ref: "#/components/parameters/Start"
        - $ref: "#/components/parameters/End"
        - $ref: "#/components/parameters/Sort"
        - $ref: "#/components/parameters/Order"
        - $ref: "#/components/parameters/ArtistId"
        - $ref: "#/components/parameters/Compilation"
        - $ref: "#/components/parameters/Starred"
        - $ref: "#/components/parameters/Missing"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Album"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthenticatedError"
  /api/song:
    get:
      tags:
        - Lists
      parameters:
        - $ref: "#/components/parameters/Start"
        - $ref: "#/components/parameters/End"
        - $ref: "#/components/parameters/Sort"
        - $ref: "#/components/parameters/Order"
        - $ref: "#/components/parameters/AlbumId"
        - $ref: "#/components/parameters/ArtistId"
        - $ref: "#/components/parameters/Starred"
        - $ref: "#/components/parameters/Title"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MediaFile"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthenticatedError"
  /api/playlist:
    get:
      tags:
        - Lists
      parameters:
        - $ref: "#/components/parameters/Start"
        - $ref: "#/components/parameters/End"
        - $ref: "#/components/parameters/Sort"
        - $ref: "#/components/parameters/Order"
        - $ref: "#/components/parameters/Query"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Playlist"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthenticatedError"
  /api/playlist/{playlistId}/tracks:
    get:
      tags:
        - Lists
      parameters:
        - name: playlistId
          in: path
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/Start"
        - $ref: "#/components/parameters/End"
        - $ref: "#/components/parameters/Sort"
        - $ref: "#/components/parameters/Order"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlaylistTrack"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthenticatedError"
components:
  parameters:
    Start:
      name: _start
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
    End:
      name: _end
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 20
    Sort:
      name: _sort
      in: query
      required: false
      schema:
        type: string
    Order:
      name: _order
      in: query
      required: false
      schema:
        type: string
        enum:
          - ASC
          - DESC
    AlbumId:
      name: album_id
      in: query
      required: false
      schema:
        type: string
    ArtistId:
      name: artist_id
      in: query
      required: false
      schema:
        type: string
    Compilation:
      name: compilation
      in: query
      required: false
      schema:
        type: boolean
    Starred:
      name: starred
      in: query
      required: false
      schema:
        type: boolean
    Missing:
      name: missing
      in: query
      required: false
      schema:
        type: boolean
    Title:
      name: title
      in: query
      required: false
      schema:
        type: string
    Query:
      name: q
      in: query
      required: false
      schema:
        type: string
  schemas:
    UnauthenticatedError:
      type: object
      required:
        - error
      properties:
        error:
          type: string
    AuthenticationResult:
      type: object
      required:
        - id
        - name
        - username
        - isAdmin
        - token
      properties:
        id:
          type: string
        name:
          type: string
        username:
          type: string
        isAdmin:
          type: boolean
        avatar:
          type: string
        subsonicSalt:
          type: string
        subsonicToken:
          type: string
        token:
          type: string
    Artist:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        albumCount:
          type: integer
        songCount:
          type: integer
    Album:
      type: object
      required:
        - id
        - libraryId
        - name
        - albumArtistId
        - albumArtist
        - allArtistIds
        - maxYear
        - minYear
        - maxOriginalYear
        - minOriginalYear
        - releases
        - compilation
        - songCount
        - duration
        - size
        - genre
        - orderAlbumName
        - orderAlbumArtistName
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        libraryId:
          type: integer
        name:
          type: string
        albumArtistId:
          type: string
        albumArtist:
          type: string
        maxYear:
          type: integer
        minYear:
          type: integer
        date:
          type: string
        maxOriginalYear:
          type: integer
        minOriginalYear:
          type: integer
        originalDate:
          type: string
        releaseDate:
          type: string
        compilation:
          type: boolean
        songCount:
          type: integer
        duration:
          type: number
          format: float32
        size:
          type: integer
        # discs:
        sortAlbumName:
          type: string
        sortAlbumArtistName:
          type: string
        orderAlbumName:
          type: string
        orderAlbumArtistName:
          type: string
        catalogNum:
          type: string
        mbzAlbumId:
          type: string
        mbzAlbumArtistId:
          type: string
        mbzAlbumType:
          type: string
        mbzAlbumComment:
          type: string
        mbzReleaseGroupId:
          type: string
        explicitStatus:
          type: string
        description:
          type: string
        smallImageUrl:
          type: string
        mediumImageUrl:
          type: string
        largeImageUrl:
          type: string
        externalUrl:
          type: string
        externalInfoUpdatedAt:
          type: string
          format: date-time
        genre:
          type: string
        genres:
          type: array
          items:
            $ref: "#/components/schemas/Genre"
        tags:
          $ref: "#/components/schemas/Tags"
        participants:
          $ref: "#/components/schemas/Participants"
        missing:
          type: boolean
        importedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        # Annotation
        playCount:
          type: integer
        playDate:
          type: string
          format: date-time
        rating:
          type: integer
        starred:
          type: boolean
        starredAt:
          type: string
          format: date-time
    Playlist:
      type: object
      required:
        - id
        - name
        - comment
        - duration
        - size
        - songCount
        - ownerName
        - ownerId
        - public
        - path
        - sync
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        name:
          type: string
        comment:
          type: string
        duration:
          type: number
          format: float32
        size:
          type: integer
          format: int64
        songCount:
          type: integer
        ownerName:
          type: string
        ownerId:
          type: string
        public:
          type: boolean
        path:
          type: string
        sync:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        # SmartPlaylist
        evaluatedAt:
          type: string
          format: date-time
    PlaylistTrack:
      allOf:
        - type: object
          required:
            - id
            - mediaFileId
            - playlistId
          properties:
            id:
              type: string
            mediaFileId:
              type: string
            playlistId:
              type: string
        - $ref: '#/components/schemas/MediaFile'
    MediaFile:
      type: object
      required:
        - id
        - libraryId
        - path
        - title
        - album
        - artist
        - albumArtist
        - albumId
        - hasCoverArt
        - trackNumber
        - discNumber
        - year
        - originalYear
        - releaseYear
        - size
        - suffix
        - duration
        - bitRate
        - sampleRate
        - genre
        - orderAlbumName
        - compilation
        - lyrics
        - createdAt
        - updatedAt
      properties:
        rating:
          type: integer
        starred:
          type: boolean
        starredAt:
          type: string
          format: date-time
        id:
          type: string
        mediaFileId:
          type: string
        playlistId:
          type: string
        playCount:
          type: integer
        playDate:
          type: string
          format: date-time
        bookmarkPosition:
          type: integer
        libraryId:
          type: integer
        path:
          type: string
        title:
          type: string
        album:
          type: string
        artistId:
          type: string
        artist:
          type: string
        albumArtistId:
          type: string
        albumArtist:
          type: string
        albumId:
          type: string
        hasCoverArt:
          type: boolean
        trackNumber:
          type: integer
        discNumber:
          type: integer
        discSubtitle:
          type: string
        year:
          type: integer
        date:
          type: string
        originalYear:
          type: integer
        originalDate:
          type: string
        releaseYear:
          type: integer
        releaseDate:
          type: string
        size:
          type: integer
        suffix:
          type: string
        duration:
          type: number
          format: float32
        bitRate:
          type: integer
        sampleRate:
          type: integer
        channels:
          type: integer
        genre:
          type: string
        genres:
          type: array
          items:
            $ref: "#/components/schemas/Genre"
        sortTitle:
          type: string
        sortAlbumName:
          type: string
        sortArtistName:
          type: string
        sortAlbumArtistName:
          type: string
        orderTitle:
          type: string
        orderAlbumName:
          type: string
        orderArtistName:
          type: string
        orderAlbumArtistName:
          type: string
        compilation:
          type: boolean
        lyrics:
          type: string
        bpm:
          type: integer
        catalogNum:
          type: string
        mbzRecordingID:
          type: string
        mbzReleaseTrackId:
          type: string
        mbzAlbumId:
          type: string
        mbzArtistId:
          type: string
        mbzAlbumArtistId:
          type: string
        mbzAlbumType:
          type: string
        mbzAlbumComment:
          type: string
        rgAlbumGain:
          type: number
          format: float64
        rgAlbumPeak:
          type: number
          format: float64
        rgTrackGain:
          type: number
          format: float64
        rgTrackPeak:
          type: number
          format: float64
        participants:
          $ref: "#/components/schemas/Participants"
        missing:
          type: boolean
        birthTime:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Genre:
      type: object
      required:
        - name
      properties:
        id:
          type: string
        name:
          type: string
    Tags:
      properties:
        recordlabel:
          type: array
          items:
            type: string
    Participants:
      properties:
        albumartist:
          type: array
          items:
            $ref: "#/components/schemas/ParticipantArtist"
        artist:
          type: array
          items:
            $ref: "#/components/schemas/ParticipantArtist"
    ParticipantArtist:
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
