#!/bin/bash
# mise description="Generate Swift code of the Open API specification."

set -e

swift-openapi-generator generate \
  --config $MISE_PROJECT_ROOT/Sources/NavidromeAPI/openapi-generator-config.yaml \
  $MISE_PROJECT_ROOT/Sources/NavidromeAPI/openapi.yaml \
  --output-directory $MISE_PROJECT_ROOT/Sources/NavidromeAPI/OpenAPI
